// Generated by Haxe 4.3.1
package haxe.lang;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class DynamicObject extends haxe.lang.HxObject
{
	static
	{
		//line 50 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.lang.DynamicObject.__hx_toString_depth = 0;
	}
	
	public DynamicObject(haxe.lang.EmptyObject empty)
	{
		//line 40 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		super(haxe.lang.EmptyObject.EMPTY);
	}
	
	
	public DynamicObject(java.lang.String[] fields, java.lang.Object[] dynamics, java.lang.String[] fields_f, double[] dynamics_f)
	{
		//line 59 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.lang.DynamicObject.__hx_ctor_haxe_lang_DynamicObject(((haxe.lang.DynamicObject) (this) ), ((java.lang.String[]) (fields) ), ((java.lang.Object[]) (dynamics) ), ((java.lang.String[]) (fields_f) ), ((double[]) (dynamics_f) ));
	}
	
	
	public DynamicObject()
	{
		//line 52 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.lang.DynamicObject.__hx_ctor_haxe_lang_DynamicObject(((haxe.lang.DynamicObject) (this) ));
	}
	
	
	protected static void __hx_ctor_haxe_lang_DynamicObject(haxe.lang.DynamicObject __hx_this, java.lang.String[] fields, java.lang.Object[] dynamics, java.lang.String[] fields_f, double[] dynamics_f)
	{
		//line 60 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_fields = fields;
		//line 61 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_dynamics = dynamics;
		//line 62 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_fields_f = fields_f;
		//line 63 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_dynamics_f = dynamics_f;
		//line 64 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_length = fields.length;
		//line 65 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_length_f = fields_f.length;
	}
	
	
	protected static void __hx_ctor_haxe_lang_DynamicObject(haxe.lang.DynamicObject __hx_this)
	{
		//line 53 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_fields = new java.lang.String[0];
		//line 54 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_dynamics = new java.lang.Object[0];
		//line 55 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_fields_f = new java.lang.String[0];
		//line 56 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		__hx_this.__hx_dynamics_f = new double[0];
	}
	
	
	public static int __hx_toString_depth;
	
	public java.lang.String[] __hx_fields;
	
	public java.lang.Object[] __hx_dynamics;
	
	public java.lang.String[] __hx_fields_f;
	
	public double[] __hx_dynamics_f;
	
	public int __hx_length;
	
	public int __hx_length_f;
	
	public boolean __hx_deleteField(java.lang.String field)
	{
		//line 69 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields, this.__hx_length);
		//line 70 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 71 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			haxe.lang.FieldLookup.removeString(this.__hx_fields, this.__hx_length, res);
			//line 72 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			haxe.lang.FieldLookup.removeDynamic(this.__hx_dynamics, this.__hx_length, res);
			//line 73 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			this.__hx_length--;
			//line 74 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return true;
		}
		
		//line 76 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res1 = haxe.lang.FieldLookup.findHash(field, this.__hx_fields_f, this.__hx_length_f);
		//line 77 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res1 >= 0 )) 
		{
			//line 78 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			haxe.lang.FieldLookup.removeString(this.__hx_fields_f, this.__hx_length_f, res1);
			//line 79 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			haxe.lang.FieldLookup.removeFloat(this.__hx_dynamics_f, this.__hx_length_f, res1);
			//line 80 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			this.__hx_length_f--;
			//line 81 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return true;
		}
		
		//line 83 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return false;
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 87 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields, this.__hx_length);
		//line 88 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 89 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.__hx_dynamics[res];
		}
		
		//line 91 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields_f, this.__hx_length_f);
		//line 92 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 93 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.__hx_dynamics_f[res];
		}
		
		//line 96 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (isCheck) 
		{
			//line 96 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return haxe.lang.Runtime.undefined;
		}
		else
		{
			//line 96 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return null;
		}
		
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 100 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields, this.__hx_length);
		//line 101 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 102 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.__hx_dynamics[res] = value;
		}
		else
		{
			//line 104 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int res1 = haxe.lang.FieldLookup.findHash(field, this.__hx_fields_f, this.__hx_length_f);
			//line 105 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			if (( res1 >= 0 )) 
			{
				//line 106 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				if (haxe.lang.Runtime.isDouble(value)) 
				{
					//line 107 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
					return this.__hx_dynamics_f[res1] = ((double) (haxe.lang.Runtime.toDouble(value)) );
				}
				
				//line 110 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				haxe.lang.FieldLookup.removeString(this.__hx_fields_f, this.__hx_length_f, res1);
				//line 111 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				haxe.lang.FieldLookup.removeFloat(this.__hx_dynamics_f, this.__hx_length_f, res1);
				//line 112 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				this.__hx_length_f--;
			}
			
		}
		
		//line 116 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_fields = haxe.lang.FieldLookup.insertString(this.__hx_fields, this.__hx_length,  ~ (res) , field);
		//line 117 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_dynamics = haxe.lang.FieldLookup.insertDynamic(this.__hx_dynamics, this.__hx_length,  ~ (res) , value);
		//line 118 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_length++;
		//line 119 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return value;
	}
	
	
	@Override public double __hx_getField_f(java.lang.String field, boolean throwErrors, boolean handleProperties)
	{
		//line 123 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields_f, this.__hx_length_f);
		//line 124 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 125 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.__hx_dynamics_f[res];
		}
		
		//line 127 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields, this.__hx_length);
		//line 128 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 129 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return ((double) (haxe.lang.Runtime.toDouble(this.__hx_dynamics[res])) );
		}
		
		//line 132 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return 0.0;
	}
	
	
	@Override public double __hx_setField_f(java.lang.String field, double value, boolean handleProperties)
	{
		//line 136 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		int res = haxe.lang.FieldLookup.findHash(field, this.__hx_fields_f, this.__hx_length_f);
		//line 137 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( res >= 0 )) 
		{
			//line 138 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.__hx_dynamics_f[res] = value;
		}
		else
		{
			//line 140 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int res1 = haxe.lang.FieldLookup.findHash(field, this.__hx_fields, this.__hx_length);
			//line 141 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			if (( res1 >= 0 )) 
			{
				//line 143 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				haxe.lang.FieldLookup.removeString(this.__hx_fields, this.__hx_length, res1);
				//line 144 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				haxe.lang.FieldLookup.removeDynamic(this.__hx_dynamics, this.__hx_length, res1);
				//line 145 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				this.__hx_length--;
			}
			
		}
		
		//line 149 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_fields_f = haxe.lang.FieldLookup.insertString(this.__hx_fields_f, this.__hx_length_f,  ~ (res) , field);
		//line 150 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_dynamics_f = haxe.lang.FieldLookup.insertFloat(this.__hx_dynamics_f, this.__hx_length_f,  ~ (res) , value);
		//line 151 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		this.__hx_length_f++;
		//line 152 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return value;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 156 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		{
			//line 156 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int _g = 0;
			//line 156 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int _g1 = this.__hx_length;
			//line 156 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			while (( _g < _g1 ))
			{
				//line 156 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				int i = _g++;
				//line 157 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				baseArr.push(this.__hx_fields[i]);
			}
			
		}
		
		//line 159 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		{
			//line 159 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int _g2 = 0;
			//line 159 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int _g3 = this.__hx_length_f;
			//line 159 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			while (( _g2 < _g3 ))
			{
				//line 159 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				int i1 = _g2++;
				//line 160 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				baseArr.push(this.__hx_fields_f[i1]);
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 165 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (haxe.lang.Runtime.valEq(field, "toString")) 
		{
			//line 166 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return this.toString();
		}
		
		//line 168 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.lang.Function fn = ((haxe.lang.Function) (this.__hx_getField(field, false, false, false)) );
		//line 169 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( fn == null )) 
		{
			//line 170 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(( ( "Cannot invoke field " + field ) + ": It does not exist" ))) );
		}
		
		//line 173 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return fn.__hx_invokeDynamic(dynargs);
	}
	
	
	@Override public java.lang.String toString()
	{
		//line 177 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( haxe.lang.DynamicObject.__hx_toString_depth >= 5 )) 
		{
			//line 178 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return "...";
		}
		
		//line 180 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		 ++ haxe.lang.DynamicObject.__hx_toString_depth;
		//line 181 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		try 
		{
			//line 182 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			java.lang.String s = this.__hx_toString();
			//line 183 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			 -- haxe.lang.DynamicObject.__hx_toString_depth;
			//line 184 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return s;
		}
		catch (java.lang.Throwable _g)
		{
			//line 185 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			java.lang.Object e = ((java.lang.Object) (haxe.Exception.caught(_g).unwrap()) );
			//line 186 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			 -- haxe.lang.DynamicObject.__hx_toString_depth;
			//line 187 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			throw ((java.lang.RuntimeException) (haxe.Exception.thrown(e)) );
		}
		
		
	}
	
	
	public java.lang.String __hx_toString()
	{
		//line 192 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.lang.Function ts = ((haxe.lang.Function) (this.__hx_getField("toString", false, false, false)) );
		//line 193 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if (( ts != null )) 
		{
			//line 194 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			return haxe.lang.Runtime.toString(((haxe.lang.Function) (ts) ).__hx_invoke0_o());
		}
		
		//line 195 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		haxe.root.StringBuf ret = new haxe.root.StringBuf();
		//line 196 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		ret.add(haxe.lang.Runtime.toString("["));
		//line 196 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		java.lang.Object __temp_expr1 = ((java.lang.Object) (null) );
		//line 197 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		boolean first = true;
		//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		{
			//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			int _g = 0;
			//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			haxe.root.Array<java.lang.String> _g1 = haxe.root.Reflect.fields(this);
			//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			while (( _g < _g1.length ))
			{
				//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				java.lang.String f = _g1.__get(_g);
				//line 198 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				 ++ _g;
				//line 199 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				if (first) 
				{
					//line 200 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
					first = false;
				}
				else
				{
					//line 202 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
					ret.add(haxe.lang.Runtime.toString(","));
					//line 202 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
					java.lang.Object __temp_expr2 = ((java.lang.Object) (null) );
				}
				
				//line 203 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				ret.add(haxe.lang.Runtime.toString(" "));
				//line 203 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				java.lang.Object __temp_expr3 = ((java.lang.Object) (null) );
				//line 204 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				ret.add(haxe.lang.Runtime.toString(f));
				//line 204 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				java.lang.Object __temp_expr4 = ((java.lang.Object) (null) );
				//line 205 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				ret.add(haxe.lang.Runtime.toString(" : "));
				//line 205 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				java.lang.Object __temp_expr5 = ((java.lang.Object) (null) );
				//line 206 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				ret.add(((java.lang.Object) (haxe.root.Reflect.field(this, f)) ));
				//line 206 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
				java.lang.Object __temp_expr6 = ((java.lang.Object) (null) );
			}
			
		}
		
		//line 208 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		if ( ! (first) ) 
		{
			//line 209 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			ret.add(haxe.lang.Runtime.toString(" "));
			//line 209 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
			java.lang.Object __temp_expr7 = ((java.lang.Object) (null) );
		}
		
		//line 210 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		ret.add(haxe.lang.Runtime.toString("]"));
		//line 210 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		java.lang.Object __temp_expr8 = ((java.lang.Object) (null) );
		//line 211 "C:\\Haxe\\Haxe431\\haxe\\std\\java\\internal\\HxObject.hx"
		return ret.toString();
	}
	
	
}


