// Generated by Haxe 4.3.1
package haxe.root;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public class TestClass extends haxe.lang.HxObject
{
	public TestClass(haxe.lang.EmptyObject empty)
	{
	}
	
	
	public TestClass()
	{
		//line 17 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		haxe.root.TestClass.__hx_ctor__TestClass(this);
	}
	
	
	protected static void __hx_ctor__TestClass(haxe.root.TestClass __hx_this)
	{
		//line 18 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Create Code class!", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"TestClass", "Code.hx", "new"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (18) )) )}));
		//line 19 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		__hx_this.field = haxe.root.TestEnum.One;
	}
	
	
	public haxe.root.TestEnum field;
	
	public void increment()
	{
		//line 23 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		switch (this.field)
		{
			case One:
			{
				//line 24 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				this.field = haxe.root.TestEnum.Two;
				//line 24 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				break;
			}
			
			
			case Two:
			{
				//line 25 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				this.field = haxe.root.TestEnum.Three;
				//line 25 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				break;
			}
			
			
			default:
			{
				//line 26 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				break;
			}
			
		}
		
		//line 28 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, this.field, 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"TestClass", "Code.hx", "increment"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (28) )) )}));
	}
	
	
	@Override public java.lang.Object __hx_setField(java.lang.String field, java.lang.Object value, boolean handleProperties)
	{
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		{
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (( field != null )) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				switch (field.hashCode())
				{
					case 97427706:
					{
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						if (field.equals("field")) 
						{
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							__temp_executeDef1 = false;
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							this.field = ((haxe.root.TestEnum) (value) );
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							return value;
						}
						
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				return super.__hx_setField(field, value, handleProperties);
			}
			else
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_getField(java.lang.String field, boolean throwErrors, boolean isCheck, boolean handleProperties)
	{
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		{
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (( field != null )) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				switch (field.hashCode())
				{
					case -1339651217:
					{
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						if (field.equals("increment")) 
						{
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							__temp_executeDef1 = false;
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							return ((haxe.lang.Function) (new haxe.lang.Closure(this, "increment")) );
						}
						
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						break;
					}
					
					
					case 97427706:
					{
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						if (field.equals("field")) 
						{
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							__temp_executeDef1 = false;
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							return this.field;
						}
						
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				return super.__hx_getField(field, throwErrors, isCheck, handleProperties);
			}
			else
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				throw null;
			}
			
		}
		
	}
	
	
	@Override public java.lang.Object __hx_invokeField(java.lang.String field, java.lang.Object[] dynargs)
	{
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		{
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			boolean __temp_executeDef1 = true;
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (( field != null )) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				switch (field.hashCode())
				{
					case -1339651217:
					{
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						if (field.equals("increment")) 
						{
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							__temp_executeDef1 = false;
							//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
							this.increment();
						}
						
						//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
						break;
					}
					
					
				}
				
			}
			
			//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			if (__temp_executeDef1) 
			{
				//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
				return super.__hx_invokeField(field, dynargs);
			}
			
		}
		
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		return null;
	}
	
	
	@Override public void __hx_getFields(haxe.root.Array<java.lang.String> baseArr)
	{
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		baseArr.push("field");
		//line 14 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		super.__hx_getFields(baseArr);
	}
	
	
}


