// Generated by Haxe 4.3.1
package _Code;

import haxe.root.*;

@SuppressWarnings(value={"rawtypes", "unchecked"})
public final class Code_Fields_
{
	public static void main(String[] args)
	{
		haxe.java.Init.init();
		_Code.Code_Fields_.main();
	}
	
	public static void main()
	{
		//line 33 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		haxe.Log.trace.__hx_invoke2_o(0.0, "Hello world!", 0.0, new haxe.lang.DynamicObject(new java.lang.String[]{"className", "fileName", "methodName"}, new java.lang.Object[]{"_Code.Code_Fields_", "Code.hx", "main"}, new java.lang.String[]{"lineNumber"}, new double[]{((double) (((double) (33) )) )}));
		//line 35 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		haxe.root.TestClass c = new haxe.root.TestClass();
		//line 36 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
		{
			//line 37 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			c.increment();
			//line 37 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			c.increment();
			//line 37 "E:\\Programming\\Haxe\\reflaxe_javasources\\test\\Code.hx"
			c.increment();
		}
		
	}
	
	
}


